// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9UOTjFW7om_QOS2t7nO0eNv5wVY9B2zE',
    appId: '1:807342724442:web:6e1cd30e466d01c2d20f63',
    messagingSenderId: '807342724442',
    projectId: 'womentech-f9f91',
    authDomain: 'womentech-f9f91.firebaseapp.com',
    storageBucket: 'womentech-f9f91.firebasestorage.app',
    measurementId: 'G-XE488LMK3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTIdyEtGXD3WROqudJ-mxyfz3lO487SzU',
    appId: '1:807342724442:android:4e990f7ef6406cebd20f63',
    messagingSenderId: '807342724442',
    projectId: 'womentech-f9f91',
    storageBucket: 'womentech-f9f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrbt4e_E1iLDC3uRU6MoW5j8Kyyl_pWA',
    appId: '1:807342724442:ios:a002e1035c2a69b3d20f63',
    messagingSenderId: '807342724442',
    projectId: 'womentech-f9f91',
    storageBucket: 'womentech-f9f91.firebasestorage.app',
    iosBundleId: 'com.wtf.womentech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrbt4e_E1iLDC3uRU6MoW5j8Kyyl_pWA',
    appId: '1:807342724442:ios:a90584adf2125d9ad20f63',
    messagingSenderId: '807342724442',
    projectId: 'womentech-f9f91',
    storageBucket: 'womentech-f9f91.firebasestorage.app',
    iosBundleId: 'com.example.geolocalisation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9UOTjFW7om_QOS2t7nO0eNv5wVY9B2zE',
    appId: '1:807342724442:web:6e1cd30e466d01c2d20f63',
    messagingSenderId: '807342724442',
    projectId: 'womentech-f9f91',
    authDomain: 'womentech-f9f91.firebaseapp.com',
    storageBucket: 'womentech-f9f91.firebasestorage.app',
    measurementId: 'G-XE488LMK3N',
  );

}